version: "3.3"

services:

  db:
    image: 'mysql/mysql-server:5.7'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookingdata
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=%
    volumes:
     - ./my-datavolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
  backendserver:
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "8081:8081"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always
